const langObject = {
  en: {
    langEn: 'English',
    langRu: 'Russian',
    changeLang: 'Language',
    widget: 'Widgets',
    time: 'Time',
    date: 'Date',
    weather: 'Weather in ',
    greeting: 'Greeting',
    quote: 'js/quotesEN.json',
    quoteTitle: 'Quote',
    audioPlayer: 'Audio Player',
    gallery: 'Background image',
    wind: 'Wind speed',
    windSpeed: 'm/s',
    humidity: 'Humidity',
    placeholder: '[Enter your name]',
    placeholderCity: '[Enter city]',
    defaultCity: 'Minsk',
    morning: 'Good morning',
    afternoon: 'Good afternoon',
    evening: 'Good evening',
    night: 'Good night',
    locale: 'en-EN',
    addBtn: 'Add',
    errorNoCity: 'Such city doesn`t exist, try another one',
    errorEmptyInput: 'Empty input. Type a city and try again',
    lastUpdatedText: 'Last updated',
  },
  ru: {
    langEn: 'Английский',
    langRu: 'Русский',
    changeLang: 'Язык',
    widget: 'Виджеты',
    time: 'Время',
    date: 'Дата',
    weather: 'Погода в городе ',
    greeting: 'Приветствие',
    quote: 'js/quotesRU.json',
    quoteTitle: 'Цитата',
    audioPlayer: 'Аудиоплеер',
    gallery: 'Фоновое изображение',
    wind: 'Скорость ветра',
    windSpeed: 'м/с',
    humidity: 'Влажность воздуха',
    placeholder: '[Введите ваше имя]',
    placeholderCity: '[Введите город]',
    defaultCity: 'Минск',
    morning: 'Доброе утро',
    afternoon: 'Добрый день',
    evening: 'Добрый вечер',
    night: 'Доброй ночи',
    locale: 'ru-RU',
    addBtn: 'Добавить',
    errorNoCity: 'Такого города не найдено, попробуйте другой',
    errorEmptyInput:
      'Пустая строка. Введите город и попробуйте снова',
    lastUpdatedText: 'Последнее обновление',
  },
};

export default langObject;
